import os
import time
print("WANDU_TIMING_GAME━━━━━━━━━━━━━━━━━━━━━━━━Test.Ver") #36줄
print("📢공지사항━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("Test ver. 1.0의 새소식━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print(" 완두 '타이밍 게임'에 오신 것을 환영합니다.")
print("이제 여기에 업데이트 소식이 실릴 것입니다.")
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print('게임을 시작하시려면 "start"를 입력하세요.')
startMSG = input(">>")
if startMSG == "start":
    os.system('cls')
    print("게임 준비━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print("화살표가 옆으로 이동하는 속도를 입력하세요.(초 단위)")
    speed = input(">>")
    print("5초 후 게임이 시작됩니다.")
    time.sleep(1)
    print("4초 후 게임이 시작됩니다.")
    time.sleep(1)
    print("3초 후 게임이 시작됩니다.")
    time.sleep(1)
    print("2초 후 게임이 시작됩니다.")
    time.sleep(1)
    print("1초 후 게임이 시작됩니다.")
    time.sleep(1)
    print("게임이 시작됩니다.")
    time.sleep(0.2)
    os.system('cls')
    print("이게 서버에 있는 내용이야!!!")
